In [ ]:
# SitePulse — Data Understanding & Profiling

## Objective

This notebook performs the initial inspection and profiling of the SitePulse construction operations dataset.

The goal is to understand the structure, quality, coverage, and basic characteristics of the data before cleaning, transformation, exploratory analysis, and machine learning.

The analysis focuses on:

- dataset dimensions
- available variables
- data types
- missing values
- duplicate records
- project coverage
- date coverage
- categorical distributions
- numerical summaries
- relational consistency between datasets

In [1]:
from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"

print(f"Project root: {PROJECT_ROOT}")
print(f"Raw data directory: {RAW_DATA_DIR}")

Project root: /Users/beyzatapan/Desktop/sitepulse-construction-analytics
Raw data directory: /Users/beyzatapan/Desktop/sitepulse-construction-analytics/data/raw

In [2]:
projects = pd.read_csv(
    RAW_DATA_DIR / "projects.csv"
)

equipment = pd.read_csv(
    RAW_DATA_DIR / "equipment.csv"
)

operations = pd.read_csv(
    RAW_DATA_DIR / "daily_operations.csv"
)

print("Projects:", projects.shape)
print("Equipment:", equipment.shape)
print("Daily operations:", operations.shape)

Projects: (6, 9)
Equipment: (30, 5)
Daily operations: (1396, 15)

In [3]:
projects = pd.read_csv(
    RAW_DATA_DIR / "projects.csv"
)

equipment = pd.read_csv(
    RAW_DATA_DIR / "equipment.csv"
)

operations = pd.read_csv(
    RAW_DATA_DIR / "daily_operations.csv"
)

print("Projects:", projects.shape)
print("Equipment:", equipment.shape)
print("Daily operations:", operations.shape)

Projects: (6, 9)
Equipment: (30, 5)
Daily operations: (1396, 15)

In [4]:
operations.head()

,date,project_id,workers,equipment_hours,fuel_consumption_l,material_delivered_t,material_used_t,planned_progress_pct,actual_progress_pct,daily_cost_usd,weather,delay_hours,material_shortage_flag,equipment_breakdown_flag,fuel_anomaly_flag
0,2026-06-19,PRJ004,123.0,36.43,868.31,8.87,8.97,58.89,53.13,12043.42,Clear,6.50,0,1,1
1,2026-06-01,PRJ005,94.0,23.24,425.02,6.43,6.34,45.20,40.21,7056.71,Light Rain,1.87,0,0,0
2,2026-09-02,PRJ004,98.0,43.04,552.66,13.78,11.46,86.67,77.15,9754.64,Clear,0.26,0,0,0
3,2026-07-21,PRJ003,51.0,45.84,642.34,11.09,10.31,89.47,77.83,5222.24,Clear,0.72,0,0,0
4,2026-08-21,PRJ006,91.0,43.58,646.79,9.14,8.00,90.43,79.30,6873.02,Clear,0.00,0,0,0

In [5]:
projects.head()

,project_id,project_name,project_type,location,planned_budget_usd,planned_duration_days,start_date,base_workers,planned_end_date
0,PRJ001,Northgate Industrial Park,Industrial,Abuja,6500000,240,2026-01-05,85,2026-09-02
1,PRJ002,Riverside Secondary School,Education,Abuja,3200000,210,2026-01-19,55,2026-08-17
2,PRJ003,Central Logistics Warehouse,Warehouse,Kaduna,4100000,190,2026-02-02,65,2026-08-11
3,PRJ004,Westlink Road Expansion,Infrastructure,Abuja,8800000,270,2026-01-12,105,2026-10-09
4,PRJ005,Greenfield Residential Estate,Residential,Lagos,5750000,250,2026-02-09,95,2026-10-17

In [6]:
projects.head()

,project_id,project_name,project_type,location,planned_budget_usd,planned_duration_days,start_date,base_workers,planned_end_date
0,PRJ001,Northgate Industrial Park,Industrial,Abuja,6500000,240,2026-01-05,85,2026-09-02
1,PRJ002,Riverside Secondary School,Education,Abuja,3200000,210,2026-01-19,55,2026-08-17
2,PRJ003,Central Logistics Warehouse,Warehouse,Kaduna,4100000,190,2026-02-02,65,2026-08-11
3,PRJ004,Westlink Road Expansion,Infrastructure,Abuja,8800000,270,2026-01-12,105,2026-10-09
4,PRJ005,Greenfield Residential Estate,Residential,Lagos,5750000,250,2026-02-09,95,2026-10-17

In [7]:
equipment.head()

  equipment_id project_id equipment_type fuel_type  expected_fuel_per_hour
0        EQ001     PRJ001      Bulldozer    Diesel                    22.0
1        EQ002     PRJ001   Mobile Crane    Diesel                    13.0
2        EQ003     PRJ001   Motor Grader    Diesel                    16.0
3        EQ004     PRJ001      Generator    Diesel                    11.0
4        EQ005     PRJ002      Excavator    Diesel                    18.0

In [8]:
dataset_summary = pd.DataFrame(
    {
        "dataset": [
            "projects",
            "equipment",
            "daily_operations",
        ],
        "rows": [
            projects.shape[0],
            equipment.shape[0],
            operations.shape[0],
        ],
        "columns": [
            projects.shape[1],
            equipment.shape[1],
            operations.shape[1],
        ],
    }
)

dataset_summary

            dataset  rows  columns
0          projects     6        9
1         equipment    30        5
2  daily_operations  1396       15

In [9]:
operations.columns.tolist()

['date',
 'project_id',
 'workers',
 'equipment_hours',
 'fuel_consumption_l',
 'material_delivered_t',
 'material_used_t',
 'planned_progress_pct',
 'actual_progress_pct',
 'daily_cost_usd',
 'weather',
 'delay_hours',
 'material_shortage_flag',
 'equipment_breakdown_flag',
 'fuel_anomaly_flag']

In [10]:
operations.columns

Index(['date', 'project_id', 'workers', 'equipment_hours',
       'fuel_consumption_l', 'material_delivered_t', 'material_used_t',
       'planned_progress_pct', 'actual_progress_pct', 'daily_cost_usd',
       'weather', 'delay_hours', 'material_shortage_flag',
       'equipment_breakdown_flag', 'fuel_anomaly_flag'],
      dtype='str')

In [11]:
operations.dtypes

date                            str
project_id                      str
workers                     float64
equipment_hours             float64
fuel_consumption_l          float64
material_delivered_t        float64
material_used_t             float64
planned_progress_pct        float64
actual_progress_pct         float64
daily_cost_usd              float64
weather                         str
delay_hours                 float64
material_shortage_flag        int64
equipment_breakdown_flag      int64
fuel_anomaly_flag             int64
dtype: object

In [12]:
operations.info()

<class 'pandas.DataFrame'>
RangeIndex: 1396 entries, 0 to 1395
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      1396 non-null   str
 1   project_id                1396 non-null   str
 2   workers                   1383 non-null   float64
 3   equipment_hours           1396 non-null   float64
 4   fuel_consumption_l        1383 non-null   float64
 5   material_delivered_t      1383 non-null   float64
 6   material_used_t           1396 non-null   float64
 7   planned_progress_pct      1396 non-null   float64
 8   actual_progress_pct       1396 non-null   float64
 9   daily_cost_usd            1396 non-null   float64
 10  weather                   1383 non-null   str
 11  delay_hours               1396 non-null   float64
 12  material_shortage_flag    1396 non-null   int64
 13  equipment_breakdown_flag  1396 non-null   int64
 14  fuel_anomaly_flag         1396 non-null   int64
dtypes: float64(9), int64(3), str(3)
memory usage: 163.7 KB

In [13]:
missing_summary = pd.DataFrame(
    {
        "missing_count": operations.isna().sum(),
        "missing_percentage": (
            operations.isna().mean() * 100
        ).round(2),
    }
)

missing_summary = missing_summary[
    missing_summary["missing_count"] > 0
]

missing_summary.sort_values(
    "missing_count",
    ascending=False,
)

                      missing_count  missing_percentage
workers                          13                0.93
fuel_consumption_l               13                0.93
material_delivered_t             13                0.93
weather                          13                0.93

In [14]:
duplicate_count = operations.duplicated().sum()

duplicate_percentage = (
    duplicate_count
    / len(operations)
    * 100
)

print(f"Duplicate rows: {duplicate_count}")
print(
    f"Duplicate percentage: "
    f"{duplicate_percentage:.2f}%"
)

Duplicate rows: 6
Duplicate percentage: 0.43%

In [15]:
operations.describe().T

,count,mean,std,min,25%,50%,75%,max
workers,1383.0,83.630513,19.254225,42.00,67.0000,87.000,98.0000,131.00
equipment_hours,1396.0,34.387407,9.133025,11.31,27.8500,32.040,42.8200,55.65
fuel_consumption_l,1383.0,532.135821,143.519842,166.25,435.7200,517.390,627.6150,1236.89
material_delivered_t,1383.0,10.370904,3.658457,1.08,8.0000,10.370,12.7400,23.74
material_used_t,1396.0,9.184979,2.735838,2.33,7.2000,8.980,11.0175,20.79
planned_progress_pct,1396.0,50.193739,28.892308,0.37,25.2150,50.185,75.2050,100.00
actual_progress_pct,1396.0,44.050215,25.654802,0.29,21.5125,44.090,66.0475,89.83
daily_cost_usd,1396.0,7230.187665,1310.106867,3917.08,6300.8475,7159.715,8116.5300,12043.42
delay_hours,1396.0,1.159728,1.747148,0.00,0.0000,0.280,1.5000,12.00
material_shortage_flag,1396.0,0.062321,0.241824,0.00,0.0000,0.000,0.0000,1.00
equipment_breakdown_flag,1396.0,0.046562,0.210773,0.00,0.0000,0.000,0.0000,1.00
fuel_anomaly_flag,1396.0,0.033668,0.180437,0.00,0.0000,0.000,0.0000,1.00

In [16]:
operations.describe(
    include=["object", "str"]
).T

           count unique         top freq
date        1396    285  2026-06-19    7
project_id  1396      6      PRJ004  272
weather     1383      4       Clear  731

In [17]:
operations["project_id"].value_counts()

project_id
PRJ004    272
PRJ005    252
PRJ001    240
PRJ006    230
PRJ002    210
PRJ003    192
Name: count, dtype: int64

In [18]:
operations["project_id"].nunique()

6

In [19]:
weather_distribution = (
    operations["weather"]
    .value_counts(
        dropna=False,
        normalize=True,
    )
    .mul(100)
    .round(2)
)

weather_distribution

weather
Clear         52.36
Cloudy        23.28
Light Rain    15.54
Heavy Rain     7.88
NaN            0.93
Name: proportion, dtype: float64

In [20]:
print(
    "Earliest record:",
    operations["date"].min(),
)

print(
    "Latest record:",
    operations["date"].max(),
)

Earliest record: 2026-01-05
Latest record: 2026-10-16

In [21]:
event_summary = pd.DataFrame(

    {

        "event": [

            "Fuel anomaly",

            "Material shortage",

            "Equipment breakdown",

        ],

        "count": [

            operations[

                "fuel_anomaly_flag"

            ].sum(),

            operations[

                "material_shortage_flag"

            ].sum(),

            operations[

                "equipment_breakdown_flag"

            ].sum(),

        ],

    }

)

event_summary["percentage"] = (

    event_summary["count"]

    / len(operations)

    * 100

).round(2)

event_summary

                 event  count  percentage
0         Fuel anomaly     47        3.37
1    Material shortage     87        6.23
2  Equipment breakdown     65        4.66

In [22]:
invalid_operation_projects = set(
    operations["project_id"]
    .dropna()
    .unique()
) - set(
    projects["project_id"]
    .dropna()
    .unique()
)

invalid_operation_projects

set()

In [23]:
invalid_equipment_projects = set(
    equipment["project_id"]
    .dropna()
    .unique()
) - set(
    projects["project_id"]
    .dropna()
    .unique()
)

invalid_equipment_projects

set()

## Initial Findings

The initial profiling indicates that the SitePulse dataset contains six construction projects and approximately 1,400 daily operational records.

Several data quality issues were identified in the raw dataset:

- missing values are present in workforce, fuel consumption, material delivery, and weather variables
- duplicate operational records are present
- the `date` variable is not yet represented as a datetime data type
- controlled operational events such as fuel anomalies, material shortages, and equipment breakdowns are present

The relational checks indicate that project identifiers used in the equipment and daily operations datasets correspond to valid projects in the project master dataset.

These findings establish the main requirements for the next stage: **data cleaning and validation**.